package aws.lambda.domain;

import static lombok.AccessLevel.PRIVATE;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;
import lombok.With;
import lombok.experimental.FieldDefaults;

@With
@Builder(toBuilder = true)
@Setter
@ToString
@AllArgsConstructor
@NoArgsConstructor
@FieldDefaults(level = PRIVATE)
@DynamoDBTable(tableName = "items")
public class Item {

  String itemId;
  String name;
  String date;

  @DynamoDBHashKey
  @DynamoDBAutoGeneratedKey
  public String getItemId() {
    return itemId;
  }

  @DynamoDBAttribute
  public String getName() {
    return name;
  }

  @DynamoDBAttribute
  public String getDate() {
    return date;
  }
}
