package aws.lambda.domain.user;

import static aws.lambda.domain.user.UserType.TEACHER;
import static lombok.AccessLevel.PRIVATE;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBIndexHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTypeConvertedEnum;
import lombok.AllArgsConstructor;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;
import lombok.With;
import lombok.experimental.FieldDefaults;
import lombok.experimental.SuperBuilder;

@With
@SuperBuilder(toBuilder = true)
@Setter
@ToString(callSuper = true)
@AllArgsConstructor
@NoArgsConstructor
@FieldDefaults(level = PRIVATE)
@DynamoDBTable(tableName = "users")
public class Teacher extends User {

  String subject;

  @DynamoDBAttribute
  public String getSubject() {
    return subject;
  }

  @DynamoDBHashKey
  @DynamoDBAutoGeneratedKey
  public String getUserId() {
    return userId;
  }

  @DynamoDBAttribute
  public String getName() {
    return name;
  }

  @DynamoDBAttribute
  public String getEmail() {
    return email;
  }

  @DynamoDBAttribute
  @DynamoDBTypeConvertedEnum
  @DynamoDBIndexHashKey(globalSecondaryIndexName = "UserTypeGSI")
  public UserType getUserType() {
    return TEACHER;
  }

}
